message:
  name: Send message
  description: Send a message to a Vestaboard.
  fields:
    device_id:
      name: Device
      description: The Vestaboard to send the message to.
      required: true
      selector:
        device:
          integration: vestaboard
          multiple: true
      example: device_id
    message:
      name: Message
      description: The message to send.
      required: false
      selector:
        text:
          multiline: true
      example: This is a message
    duration:
      name: Alert Duration
      description: "Display the message as a temporary alert. The board will revert to its previous persistent message after the duration expires. Duration is in seconds."
      required: false
      selector:
        number:
          min: 10
          max: 7200
          unit_of_measurement: "seconds"
    align:
      name: Align
      description: Horizontal alignment of text. Optional, default=center
      selector:
        select:
          options:
            - "left"
            - "center"
            - "right"
      example: left
    valign:
      name: Valign
      description: Vertical alignment of text. Optional, default=middle
      selector:
        select:
          options:
            - "top"
            - "middle"
            - "bottom"
      example: top
    vbml:
      name: Vestaboard markup language
      description: "Compose a static or dynamic message using Vestaboard markup language. Requires cloud access. See https://docs.vestaboard.com/docs/vbml for more information"
      required: false
      selector:
        text:
      example: '{ "props": { "hours": "07", "minutes": "35" }, "components": [ { "style": { "justify": "center", "align": "center" }, "template": "{{ ''{{hours}}:{{minutes}}'' }}"}]}'
